CREATE TABLE [archive].[ProdCopy_Event_20170206]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordTypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhoId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhatId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsAllDayEvent] [bit] NULL,
[ActivityDateTime] [datetime] NULL,
[ActivityDate] [date] NULL,
[DurationInMinutes] [int] NULL,
[StartDateTime] [datetime] NULL,
[EndDateTime] [datetime] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPrivate] [bit] NULL,
[ShowAs] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [bit] NULL,
[IsChild] [bit] NULL,
[IsGroupEvent] [bit] NULL,
[GroupEventType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[IsArchived] [bit] NULL,
[RecurrenceActivityId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsRecurrence] [bit] NULL,
[RecurrenceStartDateTime] [datetime] NULL,
[RecurrenceEndDateOnly] [date] NULL,
[RecurrenceTimeZoneSidKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceInterval] [int] NULL,
[RecurrenceDayOfWeekMask] [int] NULL,
[RecurrenceDayOfMonth] [int] NULL,
[RecurrenceInstance] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceMonthOfYear] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReminderDateTime] [datetime] NULL,
[IsReminderSet] [bit] NULL,
[Clearslide_Content_Viewed__c] [bit] NULL,
[Call_Result__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClearSlide_Email_Viewed__c] [bit] NULL,
[Converted_Owner_ID_to_Name__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Day_of_Week__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Meeting__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MeetingNum__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Meeting_Result__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next_Step__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number_of_Days_Before_Event__c] [float] NULL,
[Reporting_Count_Activities__c] [float] NULL,
[Sales_Event__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Same_Account_Activity_Owner__c] [bit] NULL,
[Social_Selling_Event_Source__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Start_Time__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Testimonial__c] [bit] NULL,
[Testimonial_Product__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time_of_Day__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type_for_Reporting__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Social_Selling_Sent__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Social_Sell_Source__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Actions_Taken__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Call_Answered_By__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Call_Local_Presence_ID__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Call_Recording_Duration__c] [float] NULL,
[ToutApp__Tout_Call_Recording__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Campaign_Details_Link__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Campaign__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Clicked__c] [bit] NULL,
[ToutApp__Tout_Details__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Events_Tracked__c] [float] NULL,
[ToutApp__Tout_Last_Event_At__c] [datetime] NULL,
[ToutApp__Tout_Presentation_Viewed__c] [bit] NULL,
[ToutApp__Tout_Replied_At__c] [datetime] NULL,
[ToutApp__Tout_Replied__c] [bit] NULL,
[ToutApp__Tout_Sent_By__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Template_Details__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Template_Used__c] [bit] NULL,
[ToutApp__Tout_Template__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Viewed__c] [bit] NULL,
[DialSource__Call_Campaign_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Call_Disposition_DS__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Call_Ended_DS__c] [datetime] NULL,
[DialSource__Call_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Call_Placed_DS__c] [datetime] NULL,
[DialSource__Call_Started_DS__c] [datetime] NULL,
[DialSource__Recording_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Session_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dialforce__Dialsource_Call_Back_Submitted__c] [bit] NULL,
[dialforce__Dialsource_Call_Back__c] [bit] NULL,
[dialforce__RD_CallListName__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dialforce__RD_Disposition__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID_Old_Org__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Owner_Sales_Team__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reno_Bighorns_Account__c] [bit] NULL,
[ClearSlide_Link_Clicked__c] [bit] NULL,
[ClearSlide_Email_Opened__c] [bit] NULL,
[Email_Engagement_Time__c] [float] NULL,
[DSRecordingURL__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Caller_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Voicemail_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Loaddate] [datetime] NULL
)
GO
