CREATE TABLE [dbo].[loadContact_0909]
(
[Name] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_ACCT_ID__c] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID__c] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_SSID_Winner__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_FullArchitcs_IDs__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_DimCustomerIDs__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Archtics_ID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [date] NULL,
[Age] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Activity_Last_15_Days__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Eloqua7DayActivity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_com_Web_View_Last_15_Days__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MaritalStatus] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation__c] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicXCluster] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Account] [bit] NULL,
[Num_of_games_bought_Current_Season__c] [int] NULL,
[Num_of_games_attended_Current_Season__c] [int] NULL,
[Attendance_Rate_Current_Season__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total_Kings_Tix_revenue_Current_Season__c] [decimal] (16, 2) NULL,
[Total_Kings_Tix_revenue_Previous_Season__c] [decimal] (16, 2) NULL,
[Num_arena_events_bought_Current_Season__c] [int] NULL,
[Total_arena_event_Tix_Rev_Current_Season__c] [decimal] (16, 2) NULL,
[Season_Ticket_Spend_Current_Season__c] [decimal] (16, 2) NULL,
[Num_of_games_forwarded_Current_Season__c] [int] NULL,
[Num_of_games_posted_Current_Season__c] [int] NULL,
[Num_of_games_resold_Current_Season__c] [int] NULL,
[Num_seats_forwarded_Current_Season__c] [int] NULL,
[Num_seats_posted_Current_Season__c] [int] NULL,
[Num_seats_resold_Current_Season__c] [int] NULL,
[Num_games_received_via_Fwd_Current__c] [int] NULL,
[Total_Kings_Tix_Rev_Previous_Season__c] [decimal] (16, 2) NULL,
[Attendance_Rate_Previous_Season__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Num_of_games_attended_Previous_Season__c] [int] NULL,
[Num_of_games_bought_Previous_Season__c] [int] NULL,
[Num_arena_events_bought_Previous_Season__c] [int] NULL,
[Total_arena_event_Tix_Rev_Previous__c] [decimal] (16, 2) NULL,
[Season_Ticket_Spend_Previous_Season__c] [decimal] (16, 2) NULL,
[Num_games_forwarded_Previous_Season__c] [int] NULL,
[Num_games_posted_Previous_Season__c] [int] NULL,
[Num_games_resold_Previous_Season__c] [int] NULL,
[Num_seats_forwarded_Previous_Season__c] [int] NULL,
[Num_seats_posted_Previous_Season__c] [int] NULL,
[Num_seats_resold_Previous_Season__c] [int] NULL,
[Num_games_bought_resale_TM_Plus_Previous__c] [int] NULL,
[Num_games_received_via_Fwd_Previous__c] [int] NULL,
[Num_games_bought_resale_TM_Plus_Current__c] [int] NULL,
[Tot_Rev_seats_bought_resale_TM_Plus_CS__c] [decimal] (16, 2) NULL,
[Tot_rev_seats_bought_resale_TM_Plus_PS__c] [decimal] (16, 2) NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SystemModstamp] [datetime] NULL,
[LastActivityDate] [date] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[LinkedIn_Company_Id__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastCURequestDate] [datetime] NULL,
[LastCUUpdateDate] [datetime] NULL,
[EmailBouncedReason] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailBouncedDate] [datetime] NULL,
[LinkedIn_Member_Token__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadSource] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasOptedOutOfEmail] [bit] NULL,
[DoNotCall] [bit] NULL,
[CleanStatus] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eloqua_7_Day_Activity__c] [bit] NULL,
[Spouse__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_1_Age__c] [float] NULL,
[Child_2_Age__c] [float] NULL,
[Child_3_Age__c] [float] NULL,
[Inactive_Contact__c] [bit] NOT NULL,
[Inactive_Reason__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inactive_Description__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Role__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_com_Web_View__c] [bit] NULL,
[DS_Date_of_Last_Dispo__c] [date] NULL,
[DS_Last_Disposition__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_Total_Call_Count__c] [float] NULL,
[Account_Owner__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_1_Name__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_2_Name__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Child_3_Name__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Anniversary_Date__c] [date] NULL,
[acct_Email_Activity_Last_30_Days__c] [bit] NULL,
[Employer__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_ESC_Web_View__c] [bit] NULL,
[Games_Personally_Attended__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group_Events_Previous_Season__c] [float] NULL,
[acct_Kings_com_Web_View__c] [bit] NULL,
[Kings_Feedback__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marital_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicX_Cluster__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Race__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_Name__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Twitter_Handle__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation_Title__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
