CREATE TABLE [dbo].[LoadAccount_0909]
(
[SSB_CRMSYSTEM_ACCT_ID__c] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Name] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_SSID_Winner__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_DimCustomerIDs__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_FullArchitcs_IDs__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Archtics_ID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_STH_Years__c] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_STH_Flag__c] [int] NOT NULL,
[Salutation] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Season_Ticket_Spend_Previous_Season__c] [decimal] (16, 2) NULL,
[Season_Ticket_Spend_Current_Season__c] [decimal] (16, 2) NULL,
[Discretionary_Income__c] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Net_Worth__c] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LengthOfResidence] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adults_In_Household__c] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Children_Flag__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordTypeId] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SystemModstamp] [datetime] NULL,
[LastActivityDate] [date] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[Website] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhotoUrl] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Industry] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfEmployees] [int] NULL,
[IsPersonAccount] [bit] NULL,
[Group_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sic] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ownership] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rating] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CleanStatus] [int] NULL,
[AccountSource] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DunsNumber] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tradestyle] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NaicsCode] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NaicsDesc] [nvarchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearStarted] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SicDesc] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Objection_Reason_1__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Objection_Reason_2__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Objection_Reason_3__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_Loyalty_Level__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNC_Exemption__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_Season_Ticket_Holder_Since__c] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SIC_Code__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Premium_Customer__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Requested_Do_Not_Call__c] [bit] NOT NULL,
[Unqualified_Reason__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_Season_Ticket_Holder__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_2014__c] [float] NULL,
[ImportHelper__c] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Share_Partner__c] [bit] NOT NULL,
[Group_Leader__c] [bit] NOT NULL,
[STH_At_Any_Point_in_Time__c] [bit] NOT NULL,
[Suite_Server__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary_Account_Owner__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temp_import__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Engagement_Level__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_Score_09_2012__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate_Partner_Employee__c] [bit] NOT NULL,
[Arena_Group__c] [bit] NOT NULL,
[fico_score_02_2013__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Partner_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[School_District_Detail__c] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Household_Income__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Enrollment_Membership__c] [float] NULL,
[FICO_Score_10_2013__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[School_District__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Social_Selling_Source__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Past_Current_Buyer_Type_2014__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone_Notes_Primary__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_Score_02_2014__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number_of_Share_Partners__c] [float] NULL,
[FICO_Score_05_2014__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESC_Web_View__c] [bit] NULL,
[Kings_com_Web_View__c] [bit] NULL,
[FICO_Score_07_2014__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[School_Miles__c] [float] NULL,
[School_Free_Lunch_Percentage__c] [float] NULL,
[Suite_Mailer_Temp_Field__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[School_Grade_Level__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_Score__c] [float] NULL,
[Email_Activity_Last_30_Days__c] [bit] NULL,
[KOL_Prospect__c] [bit] NOT NULL,
[Cantina__c] [bit] NOT NULL,
[Past_Current_Buyer_Type_2015__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reporting_Count_Accounts__c] [float] NULL,
[Date_of_Cantina_Event__c] [date] NULL,
[Cantina_Level__c] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Activity__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group_Ranking__c] [float] NULL,
[Rollover_Deposit__c] [bit] NOT NULL,
[Year_of_Previous_Season__c] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary_Purchase_Reason__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse_Name__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attend__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STM_Notes__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2015_16_Seat_Location__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_Rollup_14_15__c] [float] NULL,
[Kings_Rollup_15_16__c] [float] NULL,
[XNo_of_Declines_in_the_Past_Year__c] [float] NULL,
[Decision_Makers_and_Roles__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Promises_Made_In_the_Past__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[How_the_account_holders_use_tickets__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attendance__c] [int] NULL,
[Parking_Purchased__c] [bit] NOT NULL,
[Additional_Notes_about_Tenure__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Temp_Field__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2015_16_Seat_Location_2__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2015_16_Seat_Location_3__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2015_16_Seat_Location_4__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group_Campaign_Source__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Will_bring_a_group_out_to_a_2nd_game__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rate_group_experience_1_10__c] [float] NULL,
[What_group_would_enjoy_the_most__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2016_17_Seat_Location_1__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2016_17_Seat_Location_2__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2016_17_Seat_Location_3__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X2016_17_Seat_Location_4__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Twitter_handle__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Upper_Level_vs_Lower_Level__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary_Market_Purchaser__c] [bit] NOT NULL,
[Past_Current_Buyer_Type_2016__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Change_Owner_Date__c] [date] NULL,
[Group_Temp_Field__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PeopleLinxAccountName__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Signed_up_for_15_16_KOL__c] [bit] NOT NULL,
[Group_Events_Previous_Season__c] [float] NULL,
[Group_Revenue_Previous_Season__c] [float] NULL,
[dialforce__DS_Date_of_Last_Dispo__c] [date] NULL,
[dialforce__DS_Last_Disposition__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dialforce__DS_Total_Call_Count__c] [float] NULL,
[Bought_tickets_to_a_game_15_16__c] [bit] NOT NULL,
[Suite_Loft_Account__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wait_List_16_17__c] [bit] NOT NULL,
[Wait_List_16_17_Games__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Premium_Seat_Location__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wait_List_16_17_Survey__c] [bit] NOT NULL,
[Jigsaw] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_Score_07_2016__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Wait_List_Source__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
