CREATE TABLE [prodcopystg].[Task]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RecordTypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhoId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhatId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivityDate] [date] NULL,
[Status] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Priority] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsHighPriority] [bit] NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [bit] NULL,
[AccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsClosed] [bit] NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[IsArchived] [bit] NULL,
[CallDurationInSeconds] [int] NULL,
[CallType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallDisposition] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CallObject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReminderDateTime] [datetime] NULL,
[IsReminderSet] [bit] NULL,
[RecurrenceActivityId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsRecurrence] [bit] NULL,
[RecurrenceStartDateOnly] [date] NULL,
[RecurrenceEndDateOnly] [date] NULL,
[RecurrenceTimeZoneSidKey] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceInterval] [int] NULL,
[RecurrenceDayOfWeekMask] [int] NULL,
[RecurrenceDayOfMonth] [int] NULL,
[RecurrenceInstance] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceMonthOfYear] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurrenceRegeneratedType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaskSubtype] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Call_Result__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Meeting__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MeetingNum__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Meeting_Result__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next_Step__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reporting_Count_Activities__c] [float] NULL,
[Sales_Event__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Same_Account_Activity_Owner__c] [bit] NULL,
[Social_Selling_Event_Source__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Start_Time__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Testimonial__c] [bit] NULL,
[Testimonial_Product__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type_for_Reporting__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Social_Selling_Sent__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Social_Sell_Source__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Actions_Taken__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Call_Answered_By__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Call_Local_Presence_ID__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Call_Recording_Duration__c] [float] NULL,
[ToutApp__Tout_Call_Recording__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Campaign_Details_Link__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Campaign__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Clicked__c] [bit] NULL,
[ToutApp__Tout_Details__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Events_Tracked__c] [float] NULL,
[ToutApp__Tout_Last_Event_At__c] [datetime] NULL,
[ToutApp__Tout_Presentation_Viewed__c] [bit] NULL,
[ToutApp__Tout_Replied_At__c] [datetime] NULL,
[ToutApp__Tout_Replied__c] [bit] NULL,
[ToutApp__Tout_Sent_By__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Template_Details__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Template_Used__c] [bit] NULL,
[ToutApp__Tout_Template__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToutApp__Tout_Viewed__c] [bit] NULL,
[DialSource__Call_Campaign_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Call_Disposition_DS__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Call_Ended_DS__c] [datetime] NULL,
[DialSource__Call_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Call_Placed_DS__c] [datetime] NULL,
[DialSource__Call_Started_DS__c] [datetime] NULL,
[DialSource__Recording_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Session_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID_Old_Org__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Owner_Sales_Team__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reno_Bighorns_Account__c] [bit] NULL,
[ClearSlide_Link_Clicked__c] [bit] NULL,
[DialSource__Caller_ID_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Voicemail_DS__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActiveRep__c] [bit] NULL,
[CLS4SF__ClearSlide_Activity_Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLS4SF__ClearSlide_Content_Link_Clicked__c] [bit] NULL,
[CLS4SF__ClearSlide_Created__c] [bit] NULL,
[CLS4SF__ClearSlide_Email_Opened__c] [bit] NULL,
[CLS4SF__ClearSlide_Engagement_Time_in_Minutes__c] [float] NULL,
[CLS4SF__ClearSlide_Engagement_Time_in_Seconds__c] [float] NULL,
[CLS4SF__ClearSlide_Forecast_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLS4SF__ClearSlide_Opportunity_Stage__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__DS_Get_Recording__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LID__Date_Sent__c] [datetime] NULL,
[LID__URL__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[loaddate] [datetime] NOT NULL CONSTRAINT [DF__Task__loaddate__57C7FD4B] DEFAULT (getdate()),
[koreps__Activity_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Activity_Sub_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Campaign_Id__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__ColorCode__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Consumption_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Date_Completed__c] [datetime] NULL,
[koreps__Deal_Sheet_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Inbound_Agent_Wait_Time_secs__c] [float] NULL,
[DialSource__Inbound_DNIS_Name__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Deal_Sheet_Line_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Inbound_DNIS__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__Inbound_Prospect_Wait_Time_secs__c] [float] NULL,
[DialSource__Inbound_Queue__c] [nvarchar] (140) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DialSource__RTPQ_Group_ID__c] [float] NULL,
[DialSource__RTPQ_Wait_Time__c] [float] NULL,
[DialSource__Recycled_Until_DS__c] [datetime] NULL,
[koreps__Due_Time__c] [datetime] NULL,
[koreps__Is_Outbound_Call__c] [bit] NULL,
[koreps__KORE_Touchpoint_ID__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__KonnectId__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__PremiumDeal_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Premium_Deal_ID_del__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Secondary_Name_ID__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Short_Description__c] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Subject__c] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__SyncPriority__c] [float] NULL,
[koreps__Task_Type__c] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Touchpoint_Amount__c] [float] NULL,
[koreps__Touchpoint__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Activation_Label__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhoCount] [int] NULL,
[WhatCount] [int] NULL
)
GO
ALTER TABLE [prodcopystg].[Task] ADD CONSTRAINT [PK__Task__3214EC0791202858] PRIMARY KEY CLUSTERED  ([Id])
GO
