CREATE TABLE [prodcopy_conv].[Campaign]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [bit] NULL,
[Name] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[ExpectedRevenue] [float] NULL,
[BudgetedCost] [float] NULL,
[ActualCost] [float] NULL,
[ExpectedResponse] [float] NULL,
[NumberSent] [float] NULL,
[IsActive] [bit] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfLeads] [int] NULL,
[NumberOfConvertedLeads] [int] NULL,
[NumberOfContacts] [int] NULL,
[NumberOfResponses] [int] NULL,
[NumberOfOpportunities] [int] NULL,
[NumberOfWonOpportunities] [int] NULL,
[AmountAllOpportunities] [float] NULL,
[AmountWonOpportunities] [float] NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[LastActivityDate] [date] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[CampaignMemberRecordTypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Target__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Interest__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticket_Type__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drop_Date__c] [date] NULL,
[DB_Campaign_Tactic__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordTypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Campaign_ID__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps__Expand_Profile_on_Activity_Screen__c] [bit] NULL,
[koreps__Show_on_Activity_Screen__c] [bit] NULL,
[koreps__AdHocCampaigns__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__Average_Gift__c] [float] NULL,
[stayclassy__Classy_Campaign_Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__Fundraiser_Alias__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__address1__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__address2__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__campaign_url__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__city__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__country__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__percent_goal_reached__c] [float] NULL,
[stayclassy__sc_event_id__c] [float] NULL,
[stayclassy__sf_contact_id__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__sf_designation_id__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__state__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__venue_name__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stayclassy__zip__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
