CREATE TABLE [prodcopy_conv].[Lead]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[IsDeleted] [bit] NULL,
[MasterRecordId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [nvarchar] (121) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Latitude] [float] NULL,
[Longitude] [float] NULL,
[Address] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhotoUrl] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadSource] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Industry] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rating] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualRevenue] [float] NULL,
[NumberOfEmployees] [int] NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasOptedOutOfEmail] [bit] NULL,
[IsConverted] [bit] NULL,
[ConvertedDate] [date] NULL,
[ConvertedAccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertedContactId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConvertedOpportunityId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsUnreadByOwner] [bit] NULL,
[LastActivityDate] [date] NULL,
[DoNotCall] [bit] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[Jigsaw] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JigsawContactId] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CleanStatus] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyDunsNumber] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailBouncedReason] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailBouncedDate] [datetime] NULL,
[Potential_Investment__c] [float] NULL,
[Purchase_Intention_Rating__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Competitors__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Interest_New__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticket_Type__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Objection_Reason_1__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Objection_Reason_2__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Objection_Reason_3__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unqualified_Reason__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birth_Date__c] [date] NULL,
[Lead_Status__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Requested_Do_Not_Call__c] [bit] NULL,
[ConvertedLead__c] [bit] NULL,
[Archtics_ID__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Temp_Field__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Fcbk_Image_Url__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Fcbk_Picture__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Fcbk_Profile_Url__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Fcbk_User_Id__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Fcbk_Username__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eloqua_7_Day_Activity__c] [bit] NULL,
[Recently_Transferred__c] [bit] NULL,
[STH_At_Any_Point_In_Time__c] [bit] NULL,
[ImportHelper__c] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Industry_Detail__c] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Alternate_Email__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[temp_import__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age_of_Lead_Days__c] [float] NULL,
[Kings_Feedback__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Transferred_Date__c] [datetime] NULL,
[Group_Category__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Engagement_Level__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B2B_Type__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lead_Source_Location__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lead_Source_Date__c] [date] NULL,
[jsImpacts__Imported_from_Jigsaw__c] [float] NULL,
[School_District__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DB_Created_Date_without_Time__c] [date] NULL,
[DB_Lead_Age__c] [float] NULL,
[Employer__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Household_Income__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marital_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expendable_Income_Code__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Enrollment_Members__c] [float] NULL,
[School_District_Detail__c] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_Score_10_2013__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_Score_02_2014__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICO_Score_05_2014__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LID__LinkedIn_Company_Id__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LID__LinkedIn_Member_Token__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Follow_Status__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Klout_Number__c] [float] NULL,
[sf4twitter__Klout_Score__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Origin__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Twitter_Bio__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Twitter_Creation_Date__c] [datetime] NULL,
[sf4twitter__Twitter_Follower_count__c] [float] NULL,
[sf4twitter__Twitter_Following_count__c] [float] NULL,
[sf4twitter__Twitter_Image_Url__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Twitter_Last_tweet__c] [datetime] NULL,
[sf4twitter__Twitter_Location__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Twitter_Picture__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Twitter_Status_count__c] [float] NULL,
[sf4twitter__Twitter_User_Id__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__Twitter_Username__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sf4twitter__followed__c] [bit] NULL,
[Lead_ID_18_Char__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SFSSDupeCatcher__Override_DupeCatcher__c] [bit] NULL,
[dialforce__DS_Date_of_Last_Dispo__c] [date] NULL,
[dialforce__DS_Last_Disposition__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dialforce__DS_Total_Call_Count__c] [float] NULL,
[zisf__ZoomInfo_Trigger__c] [bit] NULL,
[zisf__zoom_id__c] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zisf__zoom_lastupdated__c] [datetime] NULL
)
GO
