CREATE TABLE [prodcopy_conv].[dsfs__DocuSign_Status__c]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [bit] NULL,
[Name] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[LastActivityDate] [date] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[dsfs__Case__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Company__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Completed_Age__c] [float] NULL,
[dsfs__Completed_Date_Time__c] [datetime] NULL,
[dsfs__Contract__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Days_to_Complete__c] [float] NULL,
[dsfs__Declined_Date_Time__c] [datetime] NULL,
[dsfs__Declined_Reason__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__DocuSign_Envelope_ID__c] [nvarchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Envelope_Link__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Envelope_Status__c] [nvarchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Hours_to_Complete__c] [float] NULL,
[dsfs__Hrs_Sent_to_Sign__c] [float] NULL,
[dsfs__Minutes_to_Complete__c] [float] NULL,
[dsfs__Number_Completed__c] [float] NULL,
[dsfs__Opportunity__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Sender_Email__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Sender__c] [nvarchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Sent_Age__c] [float] NULL,
[dsfs__Sent_Date_Time__c] [datetime] NULL,
[dsfs__Subject__c] [nvarchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Time_to_Complete__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dsfs__Viewed_Date_Time__c] [datetime] NULL,
[dsfs__Voided_Date_Time__c] [datetime] NULL,
[dsfs__Voided_Reason__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opportunity_Link__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID_18_Char__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opportunity_Owner_Email__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Copy_Over_Opportunity_Email__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opportunity_Checkbox__c] [bit] NULL
)
GO
